### ISSUE TITLE
Change application questions and logic

### ISSUE THREAD

**Issue by davidzchen-ut** [FreetailHackers/quill#1]
## Description
Our Quill has application questions that still have MIT and HackMIT in them. We need to change them and also possibly add other custom application questions to Quill. Also, there is some code that needs to be changed in the Javascript involving minors who attend MIT can join the hackathon.

## Location of files
/app/client/views/applications/application.html
/app/client/views/applications/applicationCtrl.js
/app/client/views/admin/user/user.html

**Comment by davidzchen-ut** [comment]
This has been resolved with commit eb1dd16b3bff70d4eb0ed9323b50c71848808d35.

**Comment by aaronPTB** [comment]
This issue can be closed as well, right?
