### ISSUE TITLE
Modify Resume Upload system

### ISSUE THREAD

**Issue by shreyassood** [FreetailHackers/quill#15]
Currently takes a link to a place where one can upload (example dropbox file request), modify in such a manner that user applications can be connected to an uploaded resume within the application.

Possibly store in AWS s3?

**Comment by yursky** [comment]
Some hackathons I've seen use a shared dropbox folder that you can upload documents to. Most recently I saw this is Bitcamp's application flow.

**Comment by yursky** [comment]
Example can be seen here: https://github.com/bitcamp/quill/blob/master/app/client/views/application/application.html

```
<div class="field">
          <label>Resume*</label>
          <p>Upload a resume outlining any skills or experience you'd like to share. PDF preferred!</p>
          <a class="ui red button" target="_blank" href="https://www.dropbox.com/request/5LTOYVl3Gebh8uam9IUz">Upload</a>
        </div>
```

**Comment by copperstick6** [comment]
S3 is also incredibly cheap and convenient. We can also integrate this S3 bucket into our existing flows for other platforms that we use

**Comment by shreyassood** [comment]
Most important point of this is associating a resume to a person in the users table, since we will need that for the corporate portal, that or export all searchable fields to another external database which leads to problems of inconsistency,

**Comment by copperstick6** [comment]
Yeah. What we can also do is attach metadata/tags to each S3 object that is linked to a UUID for each user. That way if we have issues with the database, we can use the metadata/tags as backup

**Comment by yursky** [comment]
For pepper the title of the file was linked to the user's unique ID in the DB (kinda hacky imo) 

Object Tagging with S3 is a great idea @copperstick6
