### ISSUE TITLE
Develop additional application fields for emergency contact and MLH CoC

### ISSUE THREAD

**Issue by yursky** [FreetailHackers/quill#16]
For public hackathons like HackTX, there's a few more fields that we would need to get filled out during the application process.

- emergency contact information
- MLH CoC <- This is a big one if we are going to be an MLH member event.
- Maybe an additional liability waiver?

Adding both of these would be simply adding fields in the mongoose schema and then adding them as additional fields in the web form. A good first issue for someone who might be interested in getting started. This is also just a suggested feature that I think would be important later and I'm putting this up as a github issue because I'm bored and have nothing to do right now at 2:30 AM but I can't sleep because I ate some chocolate a little while ago (horrible mistake btw)

Sorry if I'm ruining your flow @shreyassood and the rest of tech team. 

✌

**Comment by shreyassood** [comment]
Quill works in an application process of 2 rounds: a basic application and then a confirmation from the user when they do all of this and other things, all of which lives here: https://github.com/FreetailHackers/quill/blob/master/app/client/views/confirmation/confirmation.html  @davidzchen-ut is working on fixing this for wholesome hacks

**Comment by yursky** [comment]
You are still using the HackMIT CoC

**Comment by yursky** [comment]
Gotcha, just wanted to point it out. The emergency contact would be a good field to add regardless 😃

**Comment by davidzchen-ut** [comment]
No worries, I'll be sure to add an emergency contact field as well.

**Comment by davidzchen-ut** [comment]
PR #25 takes care of liability and photo release waiver

**Comment by copperstick6** [comment]
Looks done to me. Closing.
