### ISSUE TITLE
Change email text (registered, admitted, accepted)

### ISSUE THREAD

**Issue by davidzchen-ut** [FreetailHackers/quill#2]
## Description
The original HackMIT email text has not been changed. We need to change it to WholesomeHack related text.

## Location of Files
/app/server/templates/email-basic/*
/app/server/templates/email-link-action/*
/app/server/templates/email-verify/*

**Comment by yursky** [comment]
This is done in commit ed1b83c1bdccd10f17fd69b9cddc3e65fa7ea20d
